#pragma once

#define BLACKBOARD_BACKGROUND_COLOR 59,60,66

#define MATERIAL_FILE_CURREN_VERSION 5
#define KE_FILE_CURRENT_VERSION 5

#define MATERIAL_FILE_MIN_VERSION 5
#define KE_FILE_MIN_VERSION 5

#define TEACH_CLIENT_VERSION 1

#define DEFAULT_FONT_SIZE 20
#define DEFAULT_LINE_WIDTH 2

#define MAX_ZOOM 1.5

#define TEXTELEMENT_TABSTOP 4

#define HIGHTITEM_BORDER 2
#define MATERIALITEM_RECT_INSIDE 2

//network
#define DEFAULT_BROADCAST_PORT 9342
//发现一个有趣的问题，server的port可以不固定，这样的话，只需要一个broadcast port了
#define DEFAULT_LISTEN_PORT 9343

#define LOKI_LISTEN_PORT 8169

#define LIVE_SINGLE_KEY "liangshi_live_single"

#define BOARD_WIDTH 1280

//#define BOARD_HEIGHT 800
//没有算任务栏1280*800,最大40,这里在减去40
#define BOARD_HEIGHT 760


